name: FlowForge Testing

on:
  push:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Check for Trailing Whitespace
      run: |
        whitespace=$(find . -type f -exec egrep -l " +$" {} \; | grep -v "\.git" | grep -v "build" | grep -v "\.egg-info" | grep -v "\.png" | grep -v "external" | grep -v "tribits" | grep -v "\_\_pycache\_\_" | grep -v "workspace" | grep -v "\.h5" | grep -v "\.pyc" | grep -v "\.pdf")
        if [[ $whitespace ]]; then
            echo "ERROR - Trailing Whitespace found!"
            echo $whitespace
            exit 1
        fi
    - name: Install dependencies and flowforge
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[test]
    - name: Lint with pylint
      run: |
        # stop the build if there are Python syntax errors or pylint warnings
        pylint ./flowforge
    - name: Test with pytest
      run: |
        pytest